name: Dependency Updates

on:
  schedule:
  # Run every Monday at 9 AM UTC
  - cron: '0 9 * * 1'
  workflow_dispatch:


jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Update backend dependencies
      working-directory: ./backend
      run: |
        npm update
        npm audit fix --force || true

    - name: Update frontend dependencies
      working-directory: ./client
      run: |
        npm update
        npm audit fix --force || true

    - name: Check for changes
      id: changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: update dependencies'
        body: |
          This PR updates dependencies to their latest versions.

          ### Changes
          - Updated backend dependencies
          - Updated frontend dependencies
          - Applied security fixes

          ### Notes
          - Please review the changes carefully
          - Run tests to ensure everything works correctly
          - Check for any breaking changes in the updated packages
        branch: chore/update-dependencies
        delete-branch: true

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        cd backend && npm ci
        cd ../client && npm ci

    - name: Run security audit
      run: |
        echo "### Security Audit Report :shield:" >> $GITHUB_STEP_SUMMARY
        echo "#### Backend" >> $GITHUB_STEP_SUMMARY
        cd backend
        if npm audit --audit-level=moderate; then
          echo "- ✅ No security vulnerabilities found" >> $GITHUB_STEP_SUMMARY
        else
          echo "- ⚠️ Security vulnerabilities detected" >> $GITHUB_STEP_SUMMARY
        fi

        echo "#### Frontend" >> $GITHUB_STEP_SUMMARY
        cd ../client
        if npm audit --audit-level=moderate; then
          echo "- ✅ No security vulnerabilities found" >> $GITHUB_STEP_SUMMARY
        else
          echo "- ⚠️ Security vulnerabilities detected" >> $GITHUB_STEP_SUMMARY
        fi 
